services:
  postgres:
    image: postgres:17-alpine
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - ordersystem_network

  api-auth:
    build:
      context: .
      dockerfile: api-01-auth-gateway/Dockerfile
    container_name: api-auth-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ordersystem_auth_db
      - APPLICATION_GATEWAY_DOWNSTREAM_URL=http://api-orders:8081
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ordersystem_network

  api-orders:
    build:
      context: .
      dockerfile: api-02-orders-crud/Dockerfile
    container_name: api-orders-crud
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ordersystem_orders_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ordersystem_network

volumes:
  postgres_data:
    name: postgres_data

networks:
  ordersystem_network:
    name: ordersystem_network
    driver: bridge
