spring:
  application:
    name: api-01-auth-gateway
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 3600000
  gateway:
    downstream-url: http://localhost:8081
